<?php

namespace App\Filament\Resources\Purchases\Pages;

use App\Filament\Resources\Purchases\PurchaseResource;
use App\Models\Inventory;
use App\Models\Purchase;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreatePurchase extends CreateRecord
{
    protected static string $resource = PurchaseResource::class;
    protected static bool $canCreateAnother=false;

    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }
    protected function beforeCreate(): void
    {
//        dd($this->data);
        $document_number = $this->data['document_number'];
        $provider_id = $this->data['provider_id'];
        $purchase = Purchase::where('document_number', $document_number)
            ->where('provider_id', $provider_id)
            ->where('status', '!=', 'Anulado')
            ->first();


        if ($purchase) {
            Notification::make()
                ->title('Error al iniciar compra')
                ->body('La compra que intenta registrar ya existe.')
                ->danger()
                ->send();
            $this->halt()->stop();
        }
    }

}
