<?php

namespace App\Filament\Resources\CreditNotePurchases\Pages;

use App\Filament\Resources\CreditNotePurchases\CreditNotePurchaseResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateCreditNotePurchase extends CreateRecord
{
    protected static string $resource = CreditNotePurchaseResource::class;
    protected static bool $canCreateAnother=false;
    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }
    public function mutateFormDataBeforeCreate(array $data): array
    {
        $data['process_document_type'] = "NC";
        $data['pruchase_condition'] = "Contado";
        return $data;

    }
}

