<?php

namespace App\Filament\Resources\CreditNotePurchases\Pages;

use Filament\Actions\EditAction;
use Log;
use Filament\Actions\DeleteAction;
use App\Filament\Resources\CreditNotePurchases\CreditNotePurchaseResource;
use App\Filament\Resources\Purchases\PurchaseResource;
use App\Services\Inventory\KardexService;
use App\Models\Inventory;
use App\Models\Provider;
use App\Models\PurchaseItem;
use App\Models\SaleItem;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;
use Livewire\Attributes\On;

class EditCreditNotePurchase extends EditRecord
{
    protected static string $resource = CreditNotePurchaseResource::class;

    protected function getHeaderActions(): array
    {
        return [
//            Actions\DeleteAction::make(),
        ];
    }

    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }

    protected function getFormActions(): array
    {
        return [
            // Acción para finalizar la venta
            Action::make('save')
                ->label('Finalizar Nota de Credito')
                ->color('success')
                ->icon('heroicon-o-check')
                ->requiresConfirmation()
                ->modalHeading('Confirmación')
                ->modalSubheading('¿Estás seguro de que deseas Finalizar esta NC?')
                ->modalButton('Sí, Finalizar Nota')
                ->action(function (EditAction $edit) {
                    $purchase = $this->record; // Obtener el registro de la compra
                    $purchaseItems = PurchaseItem::where('purchase_id', $purchase->id)->get();
                    $provider = Provider::with('pais')->find($purchase->provider_id);
                    $entity = $provider->comercial_name;
                    $pais = $provider->pais->name;

                    foreach ($purchaseItems as $item) {
                        try {
                            // Registrar nota de crédito de compra (disminuye stock)
                            // Como usan Purchase en vez de CreditNotePurchase, usamos el método directamente
                            $inventory = $item->inventory;
                            if (!$inventory) {
                                Log::error("Inventario no encontrado para el item de compra: {$item->id}");
                                continue;
                            }

                            // Obtener datos del proveedor
                            $provider = $purchase->provider()->with('pais')->first();

                            // Crear registro kardex manualmente ya que el modelo es Purchase no CreditNotePurchase
                            $previousStock = $inventory->stock;
                            $inventory->decrement('stock', $item->quantity);
                            $inventory->refresh();

                            \App\Models\Kardex::create([
                                'branch_id' => $inventory->branch_id,
                                'date' => $purchase->purchase_date,
                                'operation_type' => 'Nota de Credito Compra',
                                'operation_id' => $purchase->id,
                                'operation_detail_id' => $item->id,
                                'document_type' => 'NC-COMPRA',
                                'document_number' => $purchase->document_number,
                                'entity' => $provider->comercial_name ?? 'Proveedor',
                                'nationality' => $provider->pais->name ?? 'Salvadoreña',
                                'inventory_id' => $inventory->id,
                                'previous_stock' => $previousStock,
                                'stock_in' => 0,
                                'stock_out' => $item->quantity,
                                'stock_actual' => $inventory->stock,
                                'money_in' => 0,
                                'money_out' => round($item->quantity * $item->price, 2),
                                'money_actual' => round($inventory->stock * $item->price, 2),
                                'sale_price' => 0,
                                'purchase_price' => $item->price,
                                'promedial_cost' => $inventory->cost_without_taxes
                            ]);
                        } catch (\Exception $e) {
                            Log::error("Error al crear Kardex para NC compra: {$item->id}", [
                                'error' => $e->getMessage()
                            ]);
                        }
                    }

                    // Redirigir después de completar el proceso
                    $this->redirect(static::getResource()::getUrl('index'));

                }),

            // Acción para cancelar la venta
            Action::make('cancelSale')
                ->label('Cancelar Nota')
                ->icon('heroicon-o-no-symbol')
                ->color('danger')
                ->requiresConfirmation()
                ->modalHeading('Confirmación')
                ->modalSubheading('¿Estás seguro de que deseas cancelar esta Nota? Esta acción no se puede deshacer.')
                ->modalButton('Sí, cancelar venta')
                ->action(function (DeleteAction $delete) {


                    // Eliminar la venta y los elementos relacionados
                    PurchaseItem::where('purchase_id', $this->record->id)->delete();
                    $this->record->delete();

                    Notification::make()
                        ->title('Nota cancelada')
                        ->body('La Nota y sus elementos relacionados han sido eliminados con éxito.')
                        ->success()
                        ->send();

                    $this->redirect(static::getResource()::getUrl('index'));
                }),
        ];
    }

    #[On('refreshPurchase')]
    public function refresh(): void
    {
    }





}
