<?php

namespace App\Filament\Resources\CashboxOpens\Pages;

use App\Filament\Resources\CashboxOpens\CashboxOpenResource;
use App\Models\CashBox;
use App\Models\SaleItem;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateCashboxOpen extends CreateRecord
{
    protected static string $resource = CashboxOpenResource::class;

    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }

    protected static bool $canCreateAnother = false;
    protected function getRedirectUrl(): string
    {
        return static::getResource()::getUrl('index');
    }
    public function afterCreate()
    {
        $cashboxOpen = $this->record;
        $cashbox = CashBox::find($cashboxOpen->cashbox_id);
        $cashbox->balance = $this->record->open_amount ?? 0;
        $cashbox->is_open = 1;
        $cashbox->save();
        $this->redirect(static::getResource()::getUrl('index'));

    }


}
