<?php

namespace App\Filament\Resources\Transfers\Pages;

use Filament\Actions\DeleteAction;
use App\Filament\Resources\Transfers\TransferResource;
use App\Models\SaleItem;
use App\Models\Transfer;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateTransfer extends CreateRecord
{
    protected static bool $canCreateAnother = false;
    protected static string $resource = TransferResource::class;
    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }

    public function mutateFormDataBeforeCreate(array $data): array
    {

        $transfer_number = Transfer::where('wherehouse_from', $data['wherehouse_from'])
            ->max('transfer_number');
        $data['transfer_number'] = ($transfer_number ?? 0) + 1;
        return $data;
    }

    protected function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label('Iniciar Traslado')
                ->color('success')
                ->icon('heroicon-o-check')
                ->action('create')
                ->extraAttributes([
                    'class' => 'alig', // Tailwind para ajustar el margen alinearlo a la derecha

                ]),

            Action::make('cancelSale')
                ->label('Cancelar proceso')
                ->icon('heroicon-o-no-symbol')
                ->color('danger')
                ->requiresConfirmation()
                ->modalHeading('Confirmación!!')
                ->modalSubheading('¿Estás seguro de que deseas cancelar esta venta? Esta acción no se puede deshacer.')
                ->modalButton('Sí, cancelar venta')
                ->action(function (DeleteAction $delete) {
                    if (!$this->record) {
                        $this->redirect(static::getResource()::getUrl('index'));
                        return;
                    }

                    if ($this->record->is_order) {
                        Notification::make()
                            ->title('Error al anular venta')
                            ->body('No se puede cancelar una orden')
                            ->danger()
                            ->send();
                        return;
                    }

// Elimina la venta y los elementos relacionados
                    SaleItem::where('sale_id', $this->record->id)->delete();
                    $this->record->delete();

// Redirige al índice
                    $this->redirect(static::getResource()::getUrl('index'));

                }),
        ];
    }
}
