<?php

namespace App\Filament\Resources\Transfers\Pages;

use Filament\Actions\DeleteAction;
use Log;
use App\Filament\Resources\Transfers\TransferResource;
use App\Services\Inventory\KardexService;
use App\Models\CashBoxCorrelative;
use App\Models\Inventory;
use App\Models\Sale;
use App\Models\SaleItem;
use App\Models\Transfer;
use App\Models\TransferItems;
use App\Service\GetCashBoxOpenedService;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;
use Livewire\Attributes\On;

class EditTransfer extends EditRecord
{
    protected static string $resource = TransferResource::class;

    protected function getHeaderActions(): array
    {
        return [
        ];
    }

    #[On('refreshTransfer')]
    public function refresh(): void
    {
    }

    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }

    protected function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label('Realizar Traslado')
                ->color('primary')
                ->icon('heroicon-o-check')
                ->action('save')
                ->requiresConfirmation()
                ->extraAttributes([
                    'class' => 'alig', // Tailwind para ajustar el margen alinearlo a la derecha

                ]),

            Action::make('cancelSale')
                ->label('Cancelar venta')
                ->icon('heroicon-o-no-symbol')
                ->color('warning')
                ->requiresConfirmation()
                ->modalHeading('Confirmación!!')
                ->modalSubheading('¿Estás seguro de que deseas cancelar esta venta? Esta acción no se puede deshacer.')
                ->modalButton('Sí, cancelar venta')
                ->action(function (DeleteAction $delete) {
                    $this->record->delete();
                    TransferItems::where('sale_id', $this->record->id)->delete();
                    $this->redirect(static::getResource()::getUrl('index'));
                }),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['wherehouse_id'] = auth()->user()->employee->branch_id;
        return $data;
    }

    public function aftersave()//Disminuir el inventario
    {


        $id_transfer = $this->record->id; // Obtener el registro de la compra
        $transfer = Transfer::with('wherehouseFrom', 'wherehouseTo')->find($id_transfer);
        $transferItem = TransferItems::where('transfer_id', $transfer->id)->get();
        $client = $transfer->wherehouseFrom->name;
        $entity = $client;
        $pais = 'Salvadoreña';
        $documnetType = "Traslado #  " . $transfer->transfer_number;

        foreach ($transferItem as $item) {
            $inventory = Inventory::find($item->inventory_id);
            // Verifica si el inventario existe
            if (!$inventory) {
                Log::error("Inventario no encontrado para el item de compra: {$item->id}");
                continue; // Si no se encuentra el inventario, continua con el siguiente item
            }

            // Registrar traslado origen (salida)
            try {
                app(KardexService::class)->registrarTraslado($transfer, $item, true); // esOrigen = true
            } catch (\Exception $e) {
                Log::error("Error al crear Kardex para traslado origen: {$item->id}", [
                    'error' => $e->getMessage()
                ]);
            }
        }


        $transfer->update([
            'status_send' => 'Enviado',
        ]);


        // Redirigir después de completar el proceso
        $this->redirect(static::getResource()::getUrl('index'));
    }

}
