<?php

namespace App\Filament\Resources\Inventories\Pages;

use Filament\Actions\DeleteAction;
use App\Filament\Resources\Inventories\InventoryResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;

class EditInventory extends EditRecord
{
    protected static string $resource = InventoryResource::class;

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }
    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }

}
